export const pricingPlans = [
  {
    _id: "1",
    title: "Basic Plan",
    description:
      "Perfect for getting started, our Basic plan offers essential features at an affordable price",
    color: "#FEECA0",
    features: [
      "5 Basic DBS Checks",
      "5 Standard DBS Check",
      "ID Check",
      "Right to work in the UK",
      "Address Checks",
    ],
  },
  {
    _id: "2",
    title: "Premium Plan",
    description: "Everything in Hobby plus higher limits and team features.",
    color: "#C9DEFD",
    features: [
      "Unlimited Basic DBS Checks",
      "Unlimited Standard DBS Checks",
      "10 Enhanced DBS Checks",
      "ID check",
      "Right to work in the UK",
      "Financial probity check",
      "KYC",
      "KYB",
      "AML",
      "3 years address history",
      "3 years employment history including gap referencing",
      "Social Media Check",
    ],
  },
  {
    _id: "3",
    title: "Enterprise Plan",
    description: "Everything in Hobby plus higher limits and team features.",
    color: "#EFEAFE",
    features: [
      "Unlimited Basic DBS Checks",
      "Unlimited Standard DBS Checks",
      "10 Enhanced DBS Checks",
      "ID check",
      "Right to work in the UK",
      "Financial probity check",
      "KYC",
      "KYB",
      "AML",
      "5 years address history",
      "Directorship check",
      "Social Media Check",
    ],
  },
];
