export { default as HeroImage } from "./hero-image.gif";
export { default as WhyChooseUs1 } from "./why-choose-us-1.png";
export { default as WhyChooseUs2 } from "./why-choose-us-2.png";
export { default as WhyChooseUs3 } from "./why-choose-us-3.png";
export { default as WhyChooseUs4 } from "./why-choose-us-4.png";
export { default as WhyChooseUs5 } from "./why-choose-us-5.png";
export { default as UserAvatar } from "./avatar";
export { default as UserDesktop } from "./desktop";
export { default as SolarBill } from "./solar_bill";
export { default as FlagIcon } from "./flag";
export { default as StopIcon } from "./stop";
export { default as AnalyseIcon } from "./analyse";
export { default as UserTransparency } from "./user-transparency.png";
export { default as UserAnalysis } from "./user-analysis.png";
export { default as FlagUser } from "./flag-user.png";
export { default as ArrowRight } from "./arrow-right";
export { default as ArrowLeft } from "./arrow-left";
export { default as User1 } from "./user1.png";
export { default as User2 } from "./user2.png";
export { default as User3 } from "./user3.png";
export { default as Expert1 } from "./expert1.png";
export { default as Expert2 } from "./expert2.png";
export { default as Expert3 } from "./expert3.png";
export { default as Expert4 } from "./expert4.png";
export { default as Expert5 } from "./expert5.png";
export { default as Expert6 } from "./expert6.png";
export { default as Expert7 } from "./expert7.png";
export { default as Expert8 } from "./expert8.png";
export { default as HomeHeroSectionImage } from "./HomeHeroSectionImage.svg";
export { default as PatternImage } from "./Pattern.png";
export { default as PayInstantlyImage } from "./PayInstantly.svg";
export { default as VerifiedDataImage } from "./VerifiedData.svg";
export { default as SaferPaymentsIcon } from "./SaferPaymentsIcon.svg";
export { default as AlwaysCompliantIcon } from "./AlwaysCompliantIcon.svg";
export { default as AccountantHelpSquadIcon } from "./AccountantHelpSquadIcon.svg";
export { default as CentsPayIcon } from "./CentsPayIcon.svg";
export { default as BuiltInSecurityImage } from "./BuiltInSecurityImage.svg";
export { default as DeveloperReadyImage } from "./DeveloperReadyImage.svg";
export { default as FullyScalableImage } from "./FullyScalableImage.svg";
export { default as Avatar1 } from "./Avatar.png";
export { default as Avatar2 } from "./Avatar (1).png";
export { default as Avatar3 } from "./Avatar (2).png";
export { default as Avatar4 } from "./Avatar (3).png";
export { default as Avatar5 } from "./Avatar (4).png";
export { default as Avatar6 } from "./Avatar (5).png";
