export { default as HeroImage } from "./hero-image.gif";
export { default as WhyChooseUs1 } from "./why-choose-us-1.png";
export { default as WhyChooseUs2 } from "./why-choose-us-2.png";
export { default as WhyChooseUs3 } from "./why-choose-us-3.png";
export { default as WhyChooseUs4 } from "./why-choose-us-4.png";
export { default as WhyChooseUs5 } from "./why-choose-us-5.png";
export { default as UserAvatar } from "./avatar";
export { default as UserDesktop } from "./desktop";
export { default as SolarBill } from "./solar_bill";
export { default as FlagIcon } from "./flag";
export { default as StopIcon } from "./stop";
export { default as AnalyseIcon } from "./analyse";
export { default as UserTransparency } from "./user-transparency.png";
export { default as UserAnalysis } from "./user-analysis.png";
export { default as FlagUser } from "./flag-user.png";
export { default as ArrowRight } from "./arrow-right";
export { default as ArrowLeft } from "./arrow-left";
export { default as User1 } from "./user1.png";
export { default as User2 } from "./user2.png";
export { default as User3 } from "./user3.png";
export { default as Expert1 } from "./expert1.png";
export { default as Expert2 } from "./expert2.png";
export { default as Expert3 } from "./expert3.png";
export { default as Expert4 } from "./expert4.png";
export { default as Expert5 } from "./expert5.png";
export { default as Expert6 } from "./expert6.png";
export { default as Expert7 } from "./expert7.png";
export { default as Expert8 } from "./expert8.png";
export { default as HomeHeroSectionImage } from "./HomeHeroSectionImage.svg";
export { default as PatternImage } from "./Pattern.png";
export { default as PayInstantlyImage } from "./PayInstantly.svg";
export { default as VerifiedDataImage } from "./VerifiedData.svg";
export { default as CentsPayIcon } from "./CentsPayIcon.svg";
export { default as BuiltInSecurityImage } from "./BuiltInSecurityImage.svg";
export { default as DeveloperReadyImage } from "./DeveloperReadyImage.svg";
export { default as FullyScalableImage } from "./FullyScalableImage.svg";
export { default as Avatar1 } from "./Avatar.png";
export { default as Avatar2 } from "./Avatar (1).png";
export { default as Avatar3 } from "./Avatar (2).png";
export { default as Avatar4 } from "./Avatar (3).png";
export { default as Avatar5 } from "./Avatar (4).png";
export { default as Avatar6 } from "./Avatar (5).png";
export { default as AccountHelpSquadIcon } from "./AccountHelpSquadIcon.svg";
export { default as IdentityAndComplianceIcon } from "./IdentityAndComplianceIcon.svg";
export { default as SmartBankIcon } from "./SmartBankIcon.svg";
export { default as CardImage } from "./CardImage.svg";
export { default as CardImage1 } from "./CardImage1.svg";

export { default as WhoWeAreIcon } from "./WhoWeAreIcon.svg";
export { default as WhatWeDoIcon } from "./WhatWeDoIcon.svg";
export { default as WhyItMattersIcon } from "./WhyItMattersIcon.svg";
export { default as WhoWeServeIcon } from "./WhoWeServeIcon.svg";
export { default as FrictionlessOnboardingImage } from "./FrictionlessOnboardingImage.svg";
export { default as SmarterlendingImage } from "./SmarterlendingImage.svg";

export { default as FinancialIcon } from "./FinancialIcon.svg";
export { default as InvestmentIcon } from "./InvestmentIcon.svg";
export { default as SavingIcon } from "./SavingIcon.svg";
export { default as CryptoIcon } from "./CryptoIcon.svg";
export { default as CreditIcon } from "./CreditIcon.svg";
export { default as GoldIcon } from "./GoldIcon.svg";
export { default as leftArrowIcon } from "./leftArrowIcon.svg";
export { default as RightArrowIcon } from "./RightArrowIcon.svg";
export { default as CEOImage } from "./CEOImage.svg";
export { default as VectorIcon } from "./VectorIcon.svg";
export { default as LastSectionBackgroundImage } from "./LastSectionBackgroundImage.svg";
