export const styles = {
  botBubbleStyle: {
    background: "#F9F9F9",
    color: "#505050",
    fontWeight: 600,
    fontSize: 14,
  },
  userBubbleStyle: {
    background: "#3369FF",
    color: "#fff",
    fontWeight: 600,
    fontSize: 14,
  },
  footerStyle: { display: "none" },
  closeChatIconStyle: { marginTop: 2, marginLeft: 3 },
  headerStyle: {
    backgroundColor: "#fff",
    color: "#494949",
    backgroundImage: "none",
    fontSize: 18,
    fontWeight: 600,
    padding: "10px 8px",
  },
  chatButtonStyle: {
    backgroundImage: "none",
  },
  chatWindowStyle: {
    borderRadius: 20,
    boxShadow: "0px 0px 21.1px 0px #E1E2EED4",
    marginRight: 30,
    marginBottom: 20,
  },
  chatInputContainerStyle: {
    borderRadius: 50,
    boxShadow: "0px 0px 3px 1px #ACACAC42 inset",
    height: 50,
    margin: "0px 10px 10px 10px",
    padding: "0px 0px 0px 12px",
  },
  chatInputAreaStyle: {
    padding: 0,
    minHeight: 35,
    alignContent: "center",
    overflow: "visible",
  },
  chatInputAreaFocusedStyle: { boxShadow: "none" },
  sendButtonStyle: {
    backgroundColor: "none",
    border: "none",
    boxShadow: "none",
    marginTop: 5,
  },
  sendButtonHoveredStyle: { backgroundColor: "none", border: "none" },
  botOptionStyle: {
    backgroundColor: "#F9F9F9",
    color: "#505050",
    fontSize: 14,
    borderColor: "none",
    padding: "4px 8px",
    border: "2px solid #F9F9F9",
    transition: "border-color 0.3s ease-in-out, box-shadow 0.3s ease-in-out",
  },
  botOptionHoveredStyle: {
    color: "#505050",
    padding: "4px 8px",
    border: "2px solid #3369FF",
    backgroundColor: "#3369FF1A",
  },
  toastPromptContainerStyle: {
    bottom: 450,
  },
  toastPromptHoveredStyle: {
    borderColor: "#fdeded",
    color: "#5F2120",
    backgroundColor: "#fdeded",
    borderRadius: 20,
  },
  toastPromptStyle: {
    borderColor: "#fff",
    color: "#5F2120",
    backgroundColor: "#fdeded",
    borderRadius: 20,
  },
};
